#                      NUMPY

# BASICS

In [1]:
import numpy as np

## How To Initialise an Array:

In [2]:
a = np.array([1,2,3])

In [3]:
print (a)

[1 2 3]


In [4]:
b= np.array([[9.0, 8.0, 7.0],[6.0, 5, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


## How to Get the Dimension of the Array:

In [8]:
a.ndim

1

In [9]:
b.ndim

2

## Get the Shape of the Array: 


In [10]:
a.shape

(3,)

In [11]:
b.shape

(2, 3)

## Get the Type 

In [12]:
a.dtype

dtype('int64')

In [13]:
b.dtype

dtype('float64')

In [16]:
c= np.array([1,2,3], dtype='int16')
c.dtype

dtype('int16')

## Get the Item Size:

In [20]:
a.itemsize

8

In [21]:
b.itemsize

8

In [22]:
c.itemsize

2

## Get the Total Size:

In [26]:
a.size * a.itemsize

24

In [27]:
a.nbytes

24

In [28]:
b.nbytes

48

# ACCESSING/ CHANGING SPECIFIC ELEMENTS, ROWS, COLUMNS, ETC

In [29]:
a= np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


# Get  a specific Element

In [30]:
a[1,5]

13

In [31]:
a[1,-2]

13

# Get a specific Row

In [32]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

# Get a specific Column

In [34]:
a[:,2]

array([ 3, 10])

# Get [start:end:step]

In [37]:
a[0, 1:7:2]

array([2, 4, 6])

In [38]:
a[0, 0:7:2]

array([1, 3, 5, 7])

# Change elements

In [40]:
a[1,5]=99
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 99 14]]


In [41]:
a[:,2]= [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 99 14]]


# INITIALIZING DIFFERENT TYPES OF ARRAYS

## All Zeros 0

In [42]:
a=np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [45]:
b=np.zeros((3,3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# All 1s

In [47]:
a= np.ones((3,2,2), dtype='int32')
print(a)

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


# Initialize with any other number

In [49]:
np.full((2,2), 89, dtype= 'float32')

array([[89., 89.],
       [89., 89.]], dtype=float32)

# Initialize with Random Numbers

In [50]:
np.random.rand(3,2,2)

array([[[0.53421454, 0.19851358],
        [0.78309862, 0.98551695]],

       [[0.13776424, 0.84516038],
        [0.9035679 , 0.99440358]],

       [[0.42364126, 0.01208855],
        [0.55939667, 0.79457254]]])

In [55]:
np.random.randint(-5,7, size=(3,2,2))

array([[[-3, -1],
        [-5, -2]],

       [[-1,  2],
        [ 1,  2]],

       [[-1,  2],
        [ 3,  6]]])

# THE IDENTITY MATRIX

In [56]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [58]:
arr= np.array([1,2,3])
r1= np.repeat(arr,3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [62]:
arr= np.array([[1,2,3]])
r1= np.repeat(arr,3, axis=0)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [67]:
a= np.ones((5,5))
a[1:4,1:4]=0
a[2,2]=9
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# BE CARFUL WHEN COPYING ARRAYS

In [68]:
A= np.array([1,2,3])
B=A  # We are copyng the direction 
B[0]=99

In [69]:
print(A)

[99  2  3]


In [70]:
print(B)

[99  2  3]


In [72]:
B= A.copy()
B[0]=89
print(B)

[89  2  3]


In [73]:
print(A)

[99  2  3]
