#                      NUMPY

# BASICS

In [1]:
import numpy as np

## How To Initialise an Array:

In [2]:
a = np.array([1,2,3])

In [3]:
print (a)

[1 2 3]


In [4]:
b= np.array([[9.0, 8.0, 7.0],[6.0, 5, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


## How to Get the Dimension of the Array:

In [8]:
a.ndim

1

In [9]:
b.ndim

2

## Get the Shape of the Array: 


In [10]:
a.shape

(3,)

In [11]:
b.shape

(2, 3)

## Get the Type 

In [12]:
a.dtype

dtype('int64')

In [13]:
b.dtype

dtype('float64')

In [16]:
c= np.array([1,2,3], dtype='int16')
c.dtype

dtype('int16')

## Get the Item Size:

In [20]:
a.itemsize

8

In [21]:
b.itemsize

8

In [22]:
c.itemsize

2

## Get the Total Size:

In [26]:
a.size * a.itemsize

24

In [27]:
a.nbytes

24

In [28]:
b.nbytes

48

# ACCESSING/ CHANGING SPECIFIC ELEMENTS, ROWS, COLUMNS, ETC

In [29]:
a= np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


# Get  a specific Element

In [30]:
a[1,5]

13

In [31]:
a[1,-2]

13

# Get a specific Row

In [32]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

# Get a specific Column

In [34]:
a[:,2]

array([ 3, 10])

# Get [start:end:step]

In [37]:
a[0, 1:7:2]

array([2, 4, 6])

In [38]:
a[0, 0:7:2]

array([1, 3, 5, 7])

# Change elements

In [40]:
a[1,5]=99
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 99 14]]


In [41]:
a[:,2]= [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 99 14]]
